run-name: Build docker
name: Docker Example
on: [push]

jobs:
  building-docker:
    runs-on: ubuntu-latest
    container:
      image: docker

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build docker
        run: docker build .
