name: Environment Variable Example
run-name: Echo some env vars
on: [push]

jobs:
  Use-Env-Vars:
    runs-on: ubuntu-latest
    env:
      THIS_IS_A_SECRET: ${{ secrets.THIS_IS_A_SECRET }}

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Echo text
        run: echo "this is a common text"

      - name: Echo vars
        run: echo "here the env var value $THIS_IS_A_SECRET"
